services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    networks:
      - mariadb_network
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

  wordpressphp:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wp-data:/var/www/html/
    networks:
      - mariadb_network
      - nginx_network
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html/
    networks:
      - nginx_network

networks:
  mariadb_network:
    name: mariadb_network
  nginx_network:
    name: nginx_network

volumes:
  db-data:
    name: database
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/juan-ant/database"
  wp-data:
    name: wp
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/juan-ant/wordpress"
